"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Posts", [
      {
        color: "blonde",
        size: "medium",
        location: "976 Williams Court, Cowiche, Indiana",
        petName: "Fischer",
        email: "wstonen@gmail.com",
        phoneNumber: "(803) 411-3203",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 2,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/labrador/n02099712_1150.jpg",
        description:
          "Has a red collar with our information, last seen in williams court neighborhood. Very friendly",
      },

      {
        color: "brown",
        size: "small",
        location: "808 Coventry Road, Davenport, New Hampshire",
        petName: "Hines",
        email: "hinesmom@gmail.com",
        phoneNumber: "(928) 428-2139",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 1,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/chihuahua/n02085620_3488.jpg",
        description:
          "If found, I can give a reward. Our pet's name is Hines. We live off Coventry Road.",
      },
      {
        color: "other",
        size: "large",
        location: "834 Lake Place, Montana, Kansas",
        petName: "no collar",
        email: "keithw@gmail.com",
        phoneNumber: "(981) 437-3310",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 2,
        StatusId: 1,
        extraNotes: "found",
        url: "https://images.dog.ceo/breeds/husky/n02110185_6411.jpg",
        description:
          "Black and white husky. See left of photo. no collar or id.",
      },
      {
        color: "white",
        size: "small",
        location: "512 Vanderveer Place, Chesterfield, Delaware",
        petName: "Vera",
        email: "sgonzales@gmail.com",
        phoneNumber: "(903) 438-3865",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 1,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/frise-bichon/1.jpg",
        description:
          "Our poodle is missing. Her name is Vera. She has a purple collar. Very friendly",
      },
      {
        color: "black",
        size: "medium",
        location: "400 Denton Place, Bayview, Idaho",
        petName: "milo",
        email: "mikepatton@gmail.com",
        phoneNumber: "(908) 450-2627",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 2,
        StatusId: 2,
        extraNotes: "found",
        url:
          "https://images.dog.ceo/breeds/terrier-kerryblue/n02093859_1662.jpg",
        description:
          "Has a collar with name of Milo but unable to read to the phone number.",
      },
      {
        color: "black",
        size: "large",
        location: "793 Gallatin Place, Aguila, Minnesota",
        petName: "no collar",
        email: "jmclaughlinn@gmail.com",
        phoneNumber: "(945) 543-3503",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 2,
        StatusId: 2,
        extraNotes: "found",
        url: "https://images.dog.ceo/breeds/germanshepherd/n02106662_2337.jpg",
        description:
          "Black and brown german shepherd. Found in Gallatin neighborhood. no collar.",
      },
      {
        color: "white",
        size: "large",
        location: "467 Brigham Street, Gallina, West Virginia",
        petName: "Sonny",
        email: "shudson@gmail.com",
        phoneNumber: "(982) 541-3634",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 2,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/dane-great/n02109047_12899.jpg",
        description:
          "Our great dane is missing. Large white dog named sonny. Last seen on Brigham Street in Gallina.",
      },
      {
        color: "brown",
        size: "medium",
        location: "807 Vine Street, Barronett, Wyoming",
        petName: "Nash",
        email: "sarahg@gmail.com",
        phoneNumber: "(993) 473-3262",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 2,
        StatusId: 1,
        extraNotes: "found",
        url: "https://images.dog.ceo/breeds/boxer/n02108089_5599.jpg",
        description: "Brown boxer found on Vine Street",
      },
      {
        color: "other",
        size: "small",
        location: "153 Franklin Street, Gambrills, Louisiana",
        petName: "no collar",
        email: "msmith@gmail.com",
        phoneNumber: "(994) 433-2975",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 2,
        StatusId: 1,
        extraNotes: "found",
        url: "https://images.dog.ceo/breeds/beagle/n02088364_12756.jpg",
        description:
          "Looks to be a beagle with no collar. found at our home on Franklin Street.",
      },
      {
        color: "white",
        size: "large",
        location: "519 Halleck Street, Medford, Oregon ",
        petName: "Mable",
        email: "kmotley@gmail.com",
        phoneNumber: "(920) 566-3389",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 1,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/pyrenees/n02111500_2747.jpg",
        description: "Our dog named Mable is missing. Reward if found.",
      },
      {
        color: "brown",
        size: "small",
        location: "201 Collingwood Ave, Charleston, South Carolina",
        petName: "Elvira",
        email: "bethsmith@gmail.com",
        phoneNumber: "(862) 587-2448",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 1,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/puggle/IMG_153357.jpg",
        description:
          "Help us find our dog name Elvira. last seen on collingwood ave",
      },
      {
        color: "other",
        size: "small",
        location: "178 Bragg Street, Steinhatchee, Florida",
        petName: "tanto",
        email: "macdonaldalston@gmail.com",
        phoneNumber: "(842) 445-3869",
        createdAt: new Date(),
        updatedAt: new Date(),
        PostTypeId: 1,
        StatusId: 2,
        extraNotes: "lost",
        url: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_2994.jpg",
        description:
          "Our dog, see left of picture, is missing. His name is tanto. Last seen on Bragg Street.",
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Posts", null, {});
  },
};
